"Filed out from Dolphin Smalltalk 7"!

Core.Tests.DolphinTest subclass: #'Kernel.Tests.AbstractNamespaceTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
Kernel.Tests.AbstractNamespaceTest guid: (Core.GUID fromString: '{8509e019-ee66-42a0-9ef9-2a5afd16b048}')!
Kernel.Tests.AbstractNamespaceTest isNonInstantiable: true!
Kernel.Tests.AbstractNamespaceTest comment: ''!
!Kernel.Tests.AbstractNamespaceTest categoriesForClass!Unclassified! !
!Kernel.Tests.AbstractNamespaceTest methodsFor!

testAbsoluteName
	self subclassResponsibility!

testAbsoluteReference
	self subclassResponsibility!

testAllClasses
	self subclassResponsibility!

testIncludesKey
	self subclassResponsibility! !
!Kernel.Tests.AbstractNamespaceTest categoriesFor: #testAbsoluteName!public!unit tests! !
!Kernel.Tests.AbstractNamespaceTest categoriesFor: #testAbsoluteReference!public!unit tests! !
!Kernel.Tests.AbstractNamespaceTest categoriesFor: #testAllClasses!public! !
!Kernel.Tests.AbstractNamespaceTest categoriesFor: #testIncludesKey!public! !

