"Filed out from Dolphin Smalltalk 7"!

Core.Tests.SortAlgorithmTest subclass: #'Kernel.Tests.IntrosortAlgorithmTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
Kernel.Tests.IntrosortAlgorithmTest guid: (Core.GUID fromString: '{95f49310-1090-4e7e-a46e-bc962a8ec984}')!
Kernel.Tests.IntrosortAlgorithmTest comment: ''!
!Kernel.Tests.IntrosortAlgorithmTest categoriesForClass!Unclassified! !
!Kernel.Tests.IntrosortAlgorithmTest methodsFor!

algorithmToTest
	^IntrosortAlgorithm! !
!Kernel.Tests.IntrosortAlgorithmTest categoriesFor: #algorithmToTest!private!unit tests! !

