"Filed out from Dolphin Smalltalk 7"!

AbstractNamespace subclass: #SystemNamespace
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
SystemNamespace guid: (GUID fromString: '{4c8d0eb7-6d0e-4467-aea6-e6f1107faf7d}')!
SystemNamespace comment: 'Will become SystemDictionary'!
!SystemNamespace categoriesForClass!Kernel-Objects! !
!SystemNamespace class methodsFor!

current
	^Smalltalk! !
!SystemNamespace class categoriesFor: #current!public! !

